
# Menus
bindld = , XF86PowerOff, Power menu, exec,  blackarch-menu system
bindd = , XF86Calculator, Calculator, exec, gnome-calculator

# Control Apple Display brightness
bindd = CTRL, F1, Apple Display brightness down, exec,  blackarch-cmd-apple-display-brightness -5000
bindd = CTRL, F2, Apple Display brightness up, exec,  blackarch-cmd-apple-display-brightness +5000
bindd = SHIFT CTRL, F2, Apple Display full brightness, exec,  blackarch-cmd-apple-display-brightness +60000


