#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
exec-once = kdeconnectd
exec-once = dunst
# exec-once = waybar
# exec-once = mako 
exec-once = swaybg -i /home/blackarch/.config/blackarch/current/background -m fill
exec-once = ~/.local/share/blackarch/bin/blackarch-setup-autorotateMonitor
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

